namespace RaqmiSystem.Domain.Inventory;

/// <summary>
/// Nature of a stock movement. The KIND carries the direction: quantities are always stored
/// strictly positive, and the sign applied when summing the registry comes from here (see
/// <see cref="StockMovement.SignedQuantity"/>). <see cref="InventoryAdjustment"/> is the one
/// kind that can go both ways - its direction is carried by
/// <see cref="StockMovement.AdjustmentIsIncrease"/>.
/// </summary>
public enum StockMovementKind
{
    /// <summary>Entry from a purchase receipt (feeds the weighted-average cost).</summary>
    PurchaseEntry,

    /// <summary>Outgoing consumption by a unit (kitchen, housekeeping, maintenance...).</summary>
    Consumption,

    /// <summary>Outgoing half of an inter-warehouse transfer.</summary>
    TransferOut,

    /// <summary>Incoming half of an inter-warehouse transfer.</summary>
    TransferIn,

    /// <summary>Correction generated by validating a physical inventory count.</summary>
    InventoryAdjustment,

    /// <summary>
    /// Sortie de vente : les quantites d'un article suivi quittent le magasin parce que la
    /// facture qui les vend est EMISE. La reference du mouvement est le numero de la facture,
    /// ce qui rend la sortie idempotente (reemettre ne ressort pas) et tracable de la facture au
    /// registre. Elle n'est jamais saisie a la main : c'est l'emission qui la produit.
    /// </summary>
    Sale
}
