using RaqmiSystem.Domain.Common;

namespace RaqmiSystem.Domain.Purchasing;

/// <summary>
/// Purchase order (bon de commande). Same numbering discipline as <c>Invoice</c>: the
/// definitive number ("BC-{year}-{sequence:D6}") is only allocated at APPROVAL time, so
/// abandoned drafts never burn a slot, and the sequence follows the approval year - the year
/// the expense was actually engaged - not the (backdatable) order date.
///
/// Lifecycle: Draft (editable) -> Approved (lines frozen, sent to the supplier) ->
/// PartiallyReceived / Received as deliveries arrive - multiple partial deliveries are the
/// normal case, not the exception. Cancellation (with a mandatory reason) is only possible
/// while NOTHING has been received: once a single unit entered the stock, the order is a
/// supporting document of real stock movements and can no longer be voided.
/// </summary>
public sealed class PurchaseOrder : AuditableEntity
{
    private readonly List<PurchaseOrderLine> _lines = new();

    private PurchaseOrder()
    {
    }

    public PurchaseOrder(string supplierCode, string warehouseCode, DateOnly orderDate)
    {
        SupplierCode = Supplier.NormalizeCode(supplierCode);
        WarehouseCode = NormalizeWarehouseCode(warehouseCode);
        OrderDate = orderDate;
        Status = PurchaseOrderStatus.Draft;
    }

    /// <summary>
    /// Definitive order number ("BC-{year}-{sequence:D6}"). Null while the order is a draft:
    /// the number is only allocated at approval time.
    /// </summary>
    public string? Number { get; private set; }

    public int? ApprovedYear { get; private set; }

    public int? ApprovedSequence { get; private set; }

    public string SupplierCode { get; private set; } = string.Empty;

    /// <summary>
    /// Code of the warehouse (stock module referential) the goods are to be delivered to;
    /// every stock entry generated by a reception of this order lands there.
    /// </summary>
    public string WarehouseCode { get; private set; } = string.Empty;

    public DateOnly OrderDate { get; private set; }

    public PurchaseOrderStatus Status { get; private set; } = PurchaseOrderStatus.Draft;

    public decimal TotalExclVat { get; private set; }

    public DateTimeOffset? ApprovedAt { get; private set; }

    public string? ApprovedBy { get; private set; }

    public DateTimeOffset? CancelledAt { get; private set; }

    public string? CancelledBy { get; private set; }

    public string? CancellationReason { get; private set; }

    public IReadOnlyCollection<PurchaseOrderLine> Lines => _lines.AsReadOnly();

    public bool CanEdit => Status == PurchaseOrderStatus.Draft;

    /// <summary>
    /// True once at least one unit has been received on any line: the point of no return for
    /// cancellation, whatever the current status says.
    /// </summary>
    public bool HasAnyReceipt => _lines.Any(line => line.QuantityReceived > 0m);

    public bool CanReceive => Status is PurchaseOrderStatus.Approved or PurchaseOrderStatus.PartiallyReceived;

    public void ReplaceLines(IReadOnlyCollection<PurchaseOrderLine> lines)
    {
        ArgumentNullException.ThrowIfNull(lines);

        if (Status != PurchaseOrderStatus.Draft)
        {
            throw new InvalidOperationException("Only draft purchase orders can be modified.");
        }

        _lines.Clear();

        var lineNumber = 1;

        foreach (var line in lines)
        {
            ArgumentNullException.ThrowIfNull(line);
            line.SetLineNumber(lineNumber++);
            _lines.Add(line);
        }

        RecalculateTotals();
    }

    public void UpdateHeader(string supplierCode, string warehouseCode, DateOnly orderDate)
    {
        if (Status != PurchaseOrderStatus.Draft)
        {
            throw new InvalidOperationException("Only draft purchase orders can be modified.");
        }

        SupplierCode = Supplier.NormalizeCode(supplierCode);
        WarehouseCode = NormalizeWarehouseCode(warehouseCode);
        OrderDate = orderDate;
    }

    /// <summary>
    /// Approves the order: allocates the definitive number and freezes the lines (the entity
    /// refuses any later ReplaceLines). Approval engages the expense, hence its dedicated
    /// permission on the API side.
    /// </summary>
    public void Approve(int year, int sequence, string userName, DateTimeOffset utcNow)
    {
        if (Status != PurchaseOrderStatus.Draft)
        {
            throw new InvalidOperationException("Only draft purchase orders can be approved.");
        }

        if (_lines.Count == 0)
        {
            throw new InvalidOperationException("A purchase order requires at least one line to be approved.");
        }

        SetNumber(year, sequence);
        Status = PurchaseOrderStatus.Approved;
        ApprovedAt = utcNow;
        ApprovedBy = RequireActor(userName);
    }

    /// <summary>
    /// Re-allocates the approval number after a unique-index collision when two orders were
    /// approved concurrently for the same year - same recovery as
    /// <c>Invoice.ReassignIssueNumber</c>. Only valid on an order that has just been approved
    /// (in-memory) but whose number failed to persist.
    /// </summary>
    public void ReassignApprovalNumber(int year, int sequence)
    {
        if (Status != PurchaseOrderStatus.Approved)
        {
            throw new InvalidOperationException("Only approved purchase orders can be renumbered.");
        }

        SetNumber(year, sequence);
    }

    /// <summary>
    /// Registers one delivery: per line, the quantity received NOW (cumulated by the line into
    /// its total received). Partial deliveries are expected - the status becomes
    /// PartiallyReceived until every line is fully received, then Received automatically.
    /// Validation runs on every requested line BEFORE any mutation, so a refused receipt
    /// leaves the order untouched.
    /// </summary>
    public void RegisterReceipt(IReadOnlyDictionary<Guid, decimal> quantitiesByLineId)
    {
        ArgumentNullException.ThrowIfNull(quantitiesByLineId);

        if (!CanReceive)
        {
            throw new InvalidOperationException(Status switch
            {
                PurchaseOrderStatus.Draft => "A draft purchase order cannot be received: approve it first.",
                PurchaseOrderStatus.Received => "This purchase order has already been fully received.",
                _ => "A cancelled purchase order cannot be received."
            });
        }

        if (quantitiesByLineId.Count == 0)
        {
            throw new ArgumentException("A receipt requires at least one line.", nameof(quantitiesByLineId));
        }

        // Validate everything first: an unknown line, a non-positive or over-scaled quantity,
        // or an over-receipt on ANY line must leave EVERY line untouched.
        foreach (var (lineId, quantity) in quantitiesByLineId)
        {
            var line = _lines.SingleOrDefault(current => current.Id == lineId)
                ?? throw new ArgumentException(
                    "The receipt references a line that does not belong to this purchase order.",
                    nameof(quantitiesByLineId));

            if (quantity <= 0m)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(quantitiesByLineId),
                    quantity,
                    $"Line {line.LineNumber} ({line.ItemCode}): the received quantity must be strictly positive.");
            }

            PurchaseOrderLine.RequireMaxScale(quantity, 3, nameof(quantitiesByLineId));

            if (quantity > line.RemainingQuantity)
            {
                throw new InvalidOperationException(
                    $"Line {line.LineNumber} ({line.ItemCode}): the received quantity ({quantity}) exceeds the " +
                    $"remaining quantity to receive ({line.RemainingQuantity}).");
            }
        }

        foreach (var (lineId, quantity) in quantitiesByLineId)
        {
            _lines.Single(current => current.Id == lineId).RegisterReceipt(quantity);
        }

        Status = _lines.All(line => line.IsFullyReceived)
            ? PurchaseOrderStatus.Received
            : PurchaseOrderStatus.PartiallyReceived;
    }

    public void Cancel(string reason, string userName, DateTimeOffset utcNow)
    {
        if (Status == PurchaseOrderStatus.Cancelled)
        {
            throw new InvalidOperationException("Purchase order is already cancelled.");
        }

        // Once a single unit entered the stock, the order documents real stock movements:
        // voiding it would leave those movements without a supporting document. The check runs
        // on the receipts themselves, not only on the status, so it stays true whatever the
        // status happens to say.
        if (HasAnyReceipt || Status is PurchaseOrderStatus.PartiallyReceived or PurchaseOrderStatus.Received)
        {
            throw new InvalidOperationException(
                "A purchase order cannot be cancelled once a delivery has been received against it.");
        }

        // Validate before mutating so a rejected reason leaves the order untouched.
        var cancellationReason = RequireValue(reason, nameof(reason), 500);

        Status = PurchaseOrderStatus.Cancelled;
        CancelledAt = utcNow;
        CancelledBy = RequireActor(userName);
        CancellationReason = cancellationReason;
    }

    public static string FormatNumber(int year, int sequence)
    {
        return $"BC-{year}-{sequence:D6}";
    }

    public static string NormalizeWarehouseCode(string value)
    {
        return RequireValue(value, nameof(value), 40).ToUpperInvariant();
    }

    private void SetNumber(int year, int sequence)
    {
        if (year is < 2000 or > 2999)
        {
            throw new ArgumentOutOfRangeException(nameof(year), year, "Year is out of the supported range.");
        }

        if (sequence is < 1 or > 999999)
        {
            throw new ArgumentOutOfRangeException(nameof(sequence), sequence, "Sequence must be between 1 and 999999.");
        }

        ApprovedYear = year;
        ApprovedSequence = sequence;
        Number = FormatNumber(year, sequence);
    }

    private void RecalculateTotals()
    {
        TotalExclVat = _lines.Sum(line => line.LineTotalExclVat);
    }

    private static string RequireActor(string userName)
    {
        if (string.IsNullOrWhiteSpace(userName))
        {
            return "system";
        }

        return userName.Trim();
    }

    private static string RequireValue(string value, string argumentName, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("Value is required.", argumentName);
        }

        var trimmed = value.Trim();

        if (trimmed.Length > maxLength)
        {
            throw new ArgumentException($"Value cannot exceed {maxLength} characters.", argumentName);
        }

        return trimmed;
    }
}
