<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>soft4dz-raqmi-system-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RaqmiSystem.Application\RaqmiSystem.Application.csproj" />
    <ProjectReference Include="..\RaqmiSystem.Infrastructure\RaqmiSystem.Infrastructure.csproj" />
  </ItemGroup>
</Project>
