namespace RaqmiSystem.Application.Sync;

/// <summary>
/// One failure entry inside a batch reported by a workstation.
/// <paramref name="EventId"/> is generated by the client and is what makes the report
/// idempotent: a workstation may resend a batch it is unsure about, and the server keeps one row.
/// <paramref name="Message"/> must already be sanitised client-side - it originates from an API
/// error body, which can carry tokens or customer data.
/// </summary>
public sealed record WorkstationFailureItem(
    Guid EventId,
    string Method,
    string Path,
    int? StatusCode,
    string Kind,
    string Message,
    DateTimeOffset ClaimedAtUtc);
