using RaqmiSystem.Domain.Inventory;

namespace RaqmiSystem.Application.Inventory;

/// <summary>
/// Direct capture of a single movement: purchase entry, consumption or manual adjustment.
/// Transfers do NOT go through here (they create two linked movements atomically - see
/// <see cref="CreateStockTransferRequest"/>), and neither do the adjustments generated by
/// validating an inventory count.
/// </summary>
public sealed record CreateStockMovementRequest(
    string WarehouseCode,
    string ItemCode,
    DateOnly MovementDate,
    StockMovementKind Kind,
    decimal Quantity,
    decimal? UnitCost,
    string Reference,
    string? LotNumber,
    DateOnly? ExpiryDate,
    string? Notes,
    bool? AdjustmentIsIncrease);
