using RaqmiSystem.Domain.Common;

namespace RaqmiSystem.Domain.Sync;

/// <summary>
/// One workstation known to the deployment: a client installation that has opened a session at
/// least once. The registry is an OPERATIONAL INVENTORY, never evidence.
///
/// Two properties of this entity are deliberate and must not be "improved" without thinking:
///
/// 1. The identifier is CHOSEN BY THE CLIENT (a Guid persisted in the workstation's settings
///    file), not generated by the database. That is what makes a workstation recognisable across
///    restarts without any hardware fingerprinting. The consequence is that a client can claim
///    any identity it likes: nothing here is authenticated beyond the caller's own JWT, so this
///    data answers "what is deployed out there" and never "who did this".
///    Because the identifier is self-assigned, the EF configuration MUST declare
///    ValueGeneratedNever() on the key, otherwise EF marks a new row Modified instead of Added.
///
/// 2. There is no "online" flag, and there must never be one. A workstation that is switched off
///    says nothing on its way out - a desktop client has no reliable way to announce its own
///    death. All the server can honestly hold is the instant of the LAST CONTACT; freshness is
///    derived from it at read time, by the server, so that every screen states the same rule.
/// </summary>
public sealed class Workstation : AuditableEntity
{
    public const int LabelMaxLength = 128;
    public const int UserNameMaxLength = 128;
    public const int AppVersionMaxLength = 32;
    public const int HotelUnitCodeMaxLength = 16;

    private Workstation()
    {
    }

    private Workstation(Guid id, string label, string userName, string appVersion, string? hotelUnitCode, DateTime nowUtc)
    {
        Id = id;
        Label = Normalize(label, nameof(label), LabelMaxLength);
        LastUserName = Normalize(userName, nameof(userName), UserNameMaxLength);
        AppVersion = Normalize(appVersion, nameof(appVersion), AppVersionMaxLength);
        LastHotelUnitCode = NormalizeOptional(hotelUnitCode, HotelUnitCodeMaxLength);
        LastSeenUtc = nowUtc;
    }

    /// <summary>Human-readable name of the machine, as reported by the client.</summary>
    public string Label { get; private set; } = string.Empty;

    /// <summary>
    /// The user seen on this workstation at the LAST contact. It is overwritten at every
    /// heartbeat: this is a current-state inventory, not a history of who used the machine.
    /// </summary>
    public string LastUserName { get; private set; } = string.Empty;

    /// <summary>
    /// Client build version. Version drift across workstations is the single most useful signal
    /// in this registry: an old client talking to a newer API is a real operational hazard.
    /// </summary>
    public string AppVersion { get; private set; } = string.Empty;

    /// <summary>Hotel unit the workstation was last working on, when the client knows it.</summary>
    public string? LastHotelUnitCode { get; private set; }

    /// <summary>
    /// Instant of the last contact, in UTC, stamped BY THE SERVER. The client's own clock is
    /// never trusted for this field - a workstation with a wrong clock would otherwise appear
    /// permanently fresh or permanently silent.
    ///
    /// DateTime (Kind Utc) and not DateTimeOffset, deliberately: the value is always a UTC
    /// instant, the offset would always be zero, and the SQLite provider used by the test
    /// harness cannot ORDER BY or compare a DateTimeOffset. Keeping the richer type here would
    /// buy nothing and leave the read paths of this module untestable.
    /// </summary>
    public DateTime LastSeenUtc { get; private set; }

    /// <summary>
    /// Registers a workstation seen for the first time. <see cref="AuditableEntity.CreatedAt"/>
    /// carries the first-contact instant, so no separate FirstSeen field is kept: two fields
    /// meaning the same thing would eventually disagree.
    /// </summary>
    public static Workstation Register(
        Guid id,
        string label,
        string userName,
        string appVersion,
        string? hotelUnitCode,
        DateTime nowUtc)
    {
        if (id == Guid.Empty)
        {
            throw new ArgumentException("The workstation identifier is required.", nameof(id));
        }

        return new Workstation(id, label, userName, appVersion, hotelUnitCode, nowUtc);
    }

    /// <summary>
    /// Records a new contact. Every descriptive field is refreshed because they all describe the
    /// CURRENT state of the machine: the user can change, and the version changes at every update.
    /// </summary>
    public void Touch(string label, string userName, string appVersion, string? hotelUnitCode, DateTime nowUtc)
    {
        Label = Normalize(label, nameof(label), LabelMaxLength);
        LastUserName = Normalize(userName, nameof(userName), UserNameMaxLength);
        AppVersion = Normalize(appVersion, nameof(appVersion), AppVersionMaxLength);
        LastHotelUnitCode = NormalizeOptional(hotelUnitCode, HotelUnitCodeMaxLength);
        LastSeenUtc = nowUtc;
    }

    // Truncation rather than refusal: a heartbeat is diagnostic traffic that must never fail an
    // operator's real work. A machine name longer than the column is trimmed, never rejected.
    private static string Normalize(string value, string parameterName, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException("The value is required.", parameterName);
        }

        var trimmed = value.Trim();

        return trimmed.Length <= maxLength ? trimmed : trimmed[..maxLength];
    }

    private static string? NormalizeOptional(string? value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var trimmed = value.Trim();

        return trimmed.Length <= maxLength ? trimmed : trimmed[..maxLength];
    }
}
