using Microsoft.EntityFrameworkCore;
using RaqmiSystem.Application.Common;
using RaqmiSystem.Application.Pos;
using RaqmiSystem.Application.Security;
using RaqmiSystem.Domain.Pos;
using RaqmiSystem.Infrastructure.Persistence;

namespace RaqmiSystem.Infrastructure.Pos;

public sealed class PosService(RaqmiDbContext db) : IPosService
{
    public async Task<IReadOnlyCollection<PosOutletResponse>> ListOutletsAsync(string unit, bool inactive, CancellationToken ct) => await db.PosOutlets.AsNoTracking().Where(x=>x.HotelUnitCode==unit.ToUpper() && (inactive||x.IsActive)).OrderBy(x=>x.Name).Select(x=>new PosOutletResponse(x.Id,x.Code,x.Name,x.HotelUnitCode,x.Kind,x.IsActive)).ToArrayAsync(ct);
    public async Task<ApplicationResult<PosOutletResponse>> SaveOutletAsync(Guid? id, SavePosOutletRequest r, OperationContext c, CancellationToken ct)
    { PosOutlet e; if(id is null){ if(await db.PosOutlets.AnyAsync(x=>x.HotelUnitCode==r.HotelUnitCode.ToUpper()&&x.Code==r.Code.ToUpper(),ct)) return ApplicationResult<PosOutletResponse>.Conflict("Ce code existe déjà pour cet établissement."); e=new(r.Code,r.Name,r.HotelUnitCode,r.Kind); e.Update(r.Name,r.Kind,r.IsActive); e.MarkCreated(c.UserName,DateTimeOffset.UtcNow); db.Add(e);} else {e=await db.PosOutlets.FindAsync([id.Value],ct) ?? null!; if(e is null)return ApplicationResult<PosOutletResponse>.NotFound("Point de vente introuvable."); e.Update(r.Name,r.Kind,r.IsActive); e.MarkUpdated(c.UserName,DateTimeOffset.UtcNow);} await db.SaveChangesAsync(ct); return ApplicationResult<PosOutletResponse>.Success(Map(e)); }
    public async Task<IReadOnlyCollection<PosTableResponse>> ListTablesAsync(Guid outlet, CancellationToken ct)=>await db.PosTables.AsNoTracking().Where(x=>x.OutletId==outlet).OrderBy(x=>x.Zone).ThenBy(x=>x.Number).Select(x=>new PosTableResponse(x.Id,x.OutletId,x.Zone,x.Number,x.Seats,x.IsActive)).ToArrayAsync(ct);
    public async Task<ApplicationResult<PosTableResponse>> SaveTableAsync(Guid outlet, Guid? id, SavePosTableRequest r, OperationContext c, CancellationToken ct)
    { if(!await db.PosOutlets.AnyAsync(x=>x.Id==outlet,ct))return ApplicationResult<PosTableResponse>.NotFound("Point de vente introuvable."); PosTable e; if(id is null){e=new(outlet,r.Zone,r.Number,r.Seats);e.Update(r.Zone,r.Number,r.Seats,r.IsActive);e.MarkCreated(c.UserName,DateTimeOffset.UtcNow);db.Add(e);}else{e=await db.PosTables.FirstOrDefaultAsync(x=>x.Id==id&&x.OutletId==outlet,ct)??null!;if(e is null)return ApplicationResult<PosTableResponse>.NotFound("Table introuvable.");e.Update(r.Zone,r.Number,r.Seats,r.IsActive);e.MarkUpdated(c.UserName,DateTimeOffset.UtcNow);}await db.SaveChangesAsync(ct);return ApplicationResult<PosTableResponse>.Success(new(e.Id,e.OutletId,e.Zone,e.Number,e.Seats,e.IsActive));}
    public async Task<IReadOnlyCollection<PosProductResponse>> ListProductsAsync(Guid outlet,bool inactive,CancellationToken ct)=>await db.PosProducts.AsNoTracking().Where(x=>x.OutletId==outlet&&(inactive||x.IsActive)).OrderBy(x=>x.Category).ThenBy(x=>x.Name).Select(x=>new PosProductResponse(x.Id,x.OutletId,x.Code,x.Name,x.Category,x.Price,x.IsActive)).ToArrayAsync(ct);
    public async Task<ApplicationResult<PosProductResponse>> SaveProductAsync(Guid outlet,Guid? id,SavePosProductRequest r,OperationContext c,CancellationToken ct)
    {if(!await db.PosOutlets.AnyAsync(x=>x.Id==outlet,ct))return ApplicationResult<PosProductResponse>.NotFound("Point de vente introuvable.");PosProduct e;if(id is null){e=new(outlet,r.Code,r.Name,r.Category,r.Price);e.Update(r.Name,r.Category,r.Price,r.IsActive);e.MarkCreated(c.UserName,DateTimeOffset.UtcNow);db.Add(e);}else{e=await db.PosProducts.FirstOrDefaultAsync(x=>x.Id==id&&x.OutletId==outlet,ct)??null!;if(e is null)return ApplicationResult<PosProductResponse>.NotFound("Article introuvable.");e.Update(r.Name,r.Category,r.Price,r.IsActive);e.MarkUpdated(c.UserName,DateTimeOffset.UtcNow);}await db.SaveChangesAsync(ct);return ApplicationResult<PosProductResponse>.Success(Map(e));}
    public async Task<ApplicationResult<PosTicketResponse>> CreateTicketAsync(CreatePosTicketRequest r,OperationContext c,CancellationToken ct)
    {var outlet=await db.PosOutlets.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==r.OutletId&&x.IsActive,ct);if(outlet is null)return ApplicationResult<PosTicketResponse>.NotFound("Point de vente inactif ou introuvable.");if(r.Lines.Count==0)return ApplicationResult<PosTicketResponse>.Validation("Le ticket doit contenir au moins un article.");var ids=r.Lines.Select(x=>x.ProductId).Distinct().ToArray();var products=await db.PosProducts.Where(x=>x.OutletId==r.OutletId&&x.IsActive&&ids.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct);if(products.Count!=ids.Length)return ApplicationResult<PosTicketResponse>.Validation("Un article n'appartient pas à ce point de vente ou est inactif.");var number=$"{outlet.Code}-{DateTime.UtcNow:yyyyMMddHHmmssfff}";var ticket=new PosTicket(r.OutletId,number,r.OrderType,r.TableId,r.RoomNumber);ticket.MarkCreated(c.UserName,DateTimeOffset.UtcNow);foreach(var line in r.Lines){var p=products[line.ProductId];var e=new PosTicketLine(ticket.Id,p.Id,p.Name,line.Quantity,p.Price);e.MarkCreated(c.UserName,DateTimeOffset.UtcNow);ticket.Lines.Add(e);}db.Add(ticket);await db.SaveChangesAsync(ct);return ApplicationResult<PosTicketResponse>.Success(Map(ticket));}
    public async Task<IReadOnlyCollection<PosTicketResponse>> ListTicketsAsync(Guid outlet,DateOnly date,CancellationToken ct){var from=date.ToDateTime(TimeOnly.MinValue,DateTimeKind.Utc);var to=from.AddDays(1);return (await db.PosTickets.AsNoTracking().Include(x=>x.Lines).Where(x=>x.OutletId==outlet&&x.OpenedAt>=from&&x.OpenedAt<to).OrderByDescending(x=>x.OpenedAt).ToArrayAsync(ct)).Select(Map).ToArray();}
    public async Task<ApplicationResult<PosTicketResponse>> PayTicketAsync(Guid id,PosPaymentMethod method,OperationContext c,CancellationToken ct){var e=await db.PosTickets.Include(x=>x.Lines).FirstOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return ApplicationResult<PosTicketResponse>.NotFound("Ticket introuvable.");try{e.Pay(method);}catch(InvalidOperationException ex){return ApplicationResult<PosTicketResponse>.Conflict(ex.Message);}e.MarkUpdated(c.UserName,DateTimeOffset.UtcNow);await db.SaveChangesAsync(ct);return ApplicationResult<PosTicketResponse>.Success(Map(e));}
    public async Task<ApplicationResult<PosTicketResponse>> CancelTicketAsync(Guid id,string reason,OperationContext c,CancellationToken ct){var e=await db.PosTickets.Include(x=>x.Lines).FirstOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return ApplicationResult<PosTicketResponse>.NotFound("Ticket introuvable.");try{e.Cancel(reason);}catch(InvalidOperationException ex){return ApplicationResult<PosTicketResponse>.Conflict(ex.Message);}e.MarkUpdated(c.UserName,DateTimeOffset.UtcNow);await db.SaveChangesAsync(ct);return ApplicationResult<PosTicketResponse>.Success(Map(e));}
    public async Task<PosDashboardResponse> GetDashboardAsync(string unit,DateOnly date,CancellationToken ct){var outlets=await db.PosOutlets.AsNoTracking().Where(x=>x.HotelUnitCode==unit.ToUpper()).ToArrayAsync(ct);var ids=outlets.Select(x=>x.Id).ToArray();var from=date.ToDateTime(TimeOnly.MinValue,DateTimeKind.Utc);var to=from.AddDays(1);var tickets=await db.PosTickets.AsNoTracking().Include(x=>x.Lines).Where(x=>ids.Contains(x.OutletId)&&x.OpenedAt>=from&&x.OpenedAt<to).ToArrayAsync(ct);var paid=tickets.Where(x=>x.Status==PosTicketStatus.Paid).ToArray();var revenue=paid.Sum(x=>x.Lines.Sum(y=>y.Total));var by=outlets.Select(o=>{var rows=paid.Where(x=>x.OutletId==o.Id).ToArray();return new PosOutletSalesResponse(o.Id,o.Name,rows.Sum(x=>x.Lines.Sum(y=>y.Total)),rows.Length);}).ToArray();return new(revenue,paid.Length,tickets.Count(x=>x.Status==PosTicketStatus.Open),paid.Length==0?0:revenue/paid.Length,by);}
    private static PosOutletResponse Map(PosOutlet x)=>new(x.Id,x.Code,x.Name,x.HotelUnitCode,x.Kind,x.IsActive);
    private static PosProductResponse Map(PosProduct x)=>new(x.Id,x.OutletId,x.Code,x.Name,x.Category,x.Price,x.IsActive);
    private static PosTicketResponse Map(PosTicket x)=>new(x.Id,x.OutletId,x.Number,x.OrderType,x.TableId,x.RoomNumber,x.Status,x.OpenedAt,x.ClosedAt,x.PaymentMethod,x.Lines.Sum(l=>l.Total),x.Lines.Select(l=>new PosTicketLineResponse(l.Id,l.ProductId,l.ProductName,l.Quantity,l.UnitPrice,l.Total)).ToArray());
}
