// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaqmiSystem.Infrastructure.Persistence;

#nullable disable

namespace RaqmiSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RaqmiDbContext))]
    [Migration("20260829214749_GlobalSettings")]
    partial class GlobalSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("raqmi")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaqmiSystem.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("action");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("EntityId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", "audit");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Billing.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Ai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ai");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("customer_type");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Nif")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nif");

                    b.Property<string>("Nis")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nis");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("Rc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rc");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_customers_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.ToTable("customers", "finance", t =>
                        {
                            t.HasCheckConstraint("ck_customers_customer_type", "customer_type IN ('Company', 'Individual', 'PublicEntity')");

                            t.HasCheckConstraint("ck_customers_nif_length", "nif IS NULL OR length(nif) = 15");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Billing.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerAddressSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_address_snapshot");

                    b.Property<string>("CustomerAiSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_ai_snapshot");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name_snapshot");

                    b.Property<string>("CustomerNifSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_nif_snapshot");

                    b.Property<string>("CustomerNisSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_nis_snapshot");

                    b.Property<string>("CustomerRcSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_rc_snapshot");

                    b.Property<string>("HotelUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hotel_unit_code");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("issued_by");

                    b.Property<int?>("IssuedSequence")
                        .HasColumnType("integer")
                        .HasColumnName("issued_sequence");

                    b.Property<int?>("IssuedYear")
                        .HasColumnType("integer")
                        .HasColumnName("issued_year");

                    b.Property<string>("IssuerAddressSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer_address_snapshot");

                    b.Property<string>("IssuerAiSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("issuer_ai_snapshot");

                    b.Property<string>("IssuerNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer_name_snapshot");

                    b.Property<string>("IssuerNifSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("issuer_nif_snapshot");

                    b.Property<string>("IssuerNisSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("issuer_nis_snapshot");

                    b.Property<string>("IssuerRcSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("issuer_rc_snapshot");

                    b.Property<string>("Number")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaidBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("paid_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalExclVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_excl_vat");

                    b.Property<decimal>("TotalInclVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_incl_vat");

                    b.Property<decimal>("TotalVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_vat");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .HasDatabaseName("ix_invoices_customer_code");

                    b.HasIndex("HotelUnitCode");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("ix_invoices_invoice_date");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_invoices_status");

                    b.HasIndex("IssuedYear", "IssuedSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_issued_year_sequence");

                    b.ToTable("invoices", "finance", t =>
                        {
                            t.HasCheckConstraint("ck_invoices_status", "status IN ('Draft', 'Issued', 'Paid', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Billing.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("designation");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("LineTotalExclVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total_excl_vat");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_lines_invoice_id");

                    b.ToTable("invoice_lines", "finance", t =>
                        {
                            t.HasCheckConstraint("ck_invoice_lines_line_number_positive", "line_number >= 1");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Closing.DailyClosing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("HotelUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hotel_unit_code");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("ReopenReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reopen_reason");

                    b.Property<DateTimeOffset?>("ReopenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reopened_at");

                    b.Property<string>("ReopenedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("reopened_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("HotelUnitCode");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_daily_closings_status");

                    b.HasIndex("BusinessDate", "HotelUnitCode")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_closings_business_date_hotel_unit_code");

                    b.ToTable("daily_closings", "exploitation", t =>
                        {
                            t.HasCheckConstraint("ck_daily_closings_status", "status IN ('Closed', 'Reopened')");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("permissions", "security");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "security");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "security");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "security");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<DateTimeOffset?>("FailedLoginWindowStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_login_window_started_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedOutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_out_until");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("users", "security");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "security");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Organization.HotelUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unit_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("hotel_units", "organization", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_units_display_order_non_negative", "display_order >= 0");

                            t.HasCheckConstraint("ck_hotel_units_unit_type", "unit_type IN ('Hotel', 'Residence', 'BeachClub', 'Marina', 'Other')");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Revenue.DailyRevenue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Accommodation")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("accommodation");

                    b.Property<decimal>("Beverage")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("beverage");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("Food")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("food");

                    b.Property<string>("HotelUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hotel_unit_code");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("Other")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("other_revenue");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("submitted_by");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<string>("ValidatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("validated_by");

                    b.HasKey("Id");

                    b.HasIndex("HotelUnitCode");

                    b.HasIndex("Status");

                    b.HasIndex("BusinessDate", "HotelUnitCode")
                        .IsUnique();

                    b.ToTable("daily_revenues", "exploitation", t =>
                        {
                            t.HasCheckConstraint("ck_daily_revenues_amounts_non_negative", "accommodation >= 0 AND food >= 0 AND beverage >= 0 AND other_revenue >= 0");

                            t.HasCheckConstraint("ck_daily_revenues_status", "status IN ('Draft', 'Submitted', 'Validated', 'Rejected')");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Settings.ApplicationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuditRetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("audit_retention_days");

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_address");

                    b.Property<string>("CompanyAi")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("company_ai");

                    b.Property<string>("CompanyCity")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("company_city");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("company_email");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyNif")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("company_nif");

                    b.Property<string>("CompanyNis")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("company_nis");

                    b.Property<string>("CompanyPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("company_phone");

                    b.Property<string>("CompanyRc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("company_rc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyLabel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_label");

                    b.Property<decimal>("DefaultVatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("default_vat_rate");

                    b.Property<string>("SingletonKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("singleton_key");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("SingletonKey")
                        .IsUnique()
                        .HasDatabaseName("ux_application_settings_singleton_key");

                    b.ToTable("application_settings", "settings", t =>
                        {
                            t.HasCheckConstraint("ck_application_settings_audit_retention_days", "audit_retention_days BETWEEN 30 AND 3650");

                            t.HasCheckConstraint("ck_application_settings_company_nif_length", "company_nif IS NULL OR length(company_nif) = 15");

                            t.HasCheckConstraint("ck_application_settings_default_vat_rate", "CAST(default_vat_rate AS numeric) IN (0, 9, 19)");

                            t.HasCheckConstraint("ck_application_settings_singleton", "singleton_key = 'GLOBAL'");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Treasury.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_bank_accounts_is_active");

                    b.ToTable("bank_accounts", "finance");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Treasury.CashReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BankAccountCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("bank_account_code");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<string>("HotelUnitCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hotel_unit_code");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date")
                        .HasColumnName("receipt_date");

                    b.Property<string>("Reference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountCode");

                    b.HasIndex("HotelUnitCode");

                    b.HasIndex("Method")
                        .HasDatabaseName("ix_cash_receipts_method");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cash_receipts_status");

                    b.HasIndex("ReceiptDate", "HotelUnitCode")
                        .HasDatabaseName("ix_cash_receipts_receipt_date_hotel_unit_code");

                    b.ToTable("cash_receipts", "finance", t =>
                        {
                            t.HasCheckConstraint("ck_cash_receipts_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_cash_receipts_method", "method IN ('Cash', 'Card', 'Cheque', 'BankTransfer')");

                            t.HasCheckConstraint("ck_cash_receipts_status", "status IN ('Draft', 'Confirmed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Treasury.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("approved_by");

                    b.Property<string>("BankAccountCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("bank_account_code");

                    b.Property<string>("Beneficiary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beneficiary");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaidBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("paid_by");

                    b.Property<string>("Reference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountCode");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_payment_orders_due_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_payment_orders_status");

                    b.ToTable("payment_orders", "finance", t =>
                        {
                            t.HasCheckConstraint("ck_payment_orders_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_payment_orders_status", "status IN ('Draft', 'Approved', 'Paid', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Billing.Invoice", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Billing.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaqmiSystem.Domain.Organization.HotelUnit", null)
                        .WithMany()
                        .HasForeignKey("HotelUnitCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Billing.InvoiceLine", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Billing.Invoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Closing.DailyClosing", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Organization.HotelUnit", null)
                        .WithMany()
                        .HasForeignKey("HotelUnitCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaqmiSystem.Domain.Identity.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaqmiSystem.Domain.Identity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Revenue.DailyRevenue", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Organization.HotelUnit", null)
                        .WithMany()
                        .HasForeignKey("HotelUnitCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Treasury.CashReceipt", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Treasury.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaqmiSystem.Domain.Organization.HotelUnit", null)
                        .WithMany()
                        .HasForeignKey("HotelUnitCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Treasury.PaymentOrder", b =>
                {
                    b.HasOne("RaqmiSystem.Domain.Treasury.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Billing.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("RaqmiSystem.Domain.Identity.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
